server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
    session:
      timeout: 3000

spring:
  datasource:
    hikari:
      driver-class-name: org.sqlite.JDBC
      jdbc-url: "jdbc:sqlite:D:/Project/CallbusAPI/callbus_db/callbusAPI.db"
      auto-commit: false
      connection-test-query: SELECT 1
      connection-timeout: 3000
    tomcat:
      max-idle: 20
      min-idle: 15
      max-active: 50
      max-wait: 20000
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    show-sql: true
    database-platform: "com.callbus.restapi.core.dialect.SQLiteDialect"